// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    structorySidebar: [
        {type: 'autogenerated', dirName: 'structory'},
        {
            type: 'link',
            label: 'Changelog',
            href: '/structory-changelog',
        }
    ],
    dadaGravesSidebar: [
        {type: 'autogenerated', dirName: 'dadagraves'},
        {
            type: 'link',
            label: 'Changelog',
            href: '/dadagraves-changelog',
        }
    ],
    dadaEventDirectorSidebar: [
        {type: 'autogenerated', dirName: 'eventdirector'}
    ],
    dadaProgressionsSidebar: [
        {type: 'autogenerated', dirName: 'dadaprogressions'},
        {
            type: 'link',
            label: 'Changelog',
            href: '/dadaprogressions-changelog',
        }
    ],
    dadaDndSidebar: [
        {type: 'autogenerated', dirName: 'dnd'}
    ],
};

export default sidebars;
